# Generated by Django 4.0.2 on 2022-02-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('dia_hora_booking', models.DateTimeField()),
                ('solicitud_especial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_platillo', models.CharField(max_length=50)),
                ('ingredientes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promocion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('promocion_image', models.ImageField(blank=True, upload_to='media', verbose_name='view')),
            ],
        ),
        migrations.CreateModel(
            name='restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_restaurant', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1024)),
                ('restaurant_image', models.ImageField(blank=True, upload_to='media', verbose_name='view')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contactmail', models.CharField(max_length=30)),
                ('cellphone', models.PositiveIntegerField()),
            ],
        ),
    ]
