# Generated by Django 4.0.2 on 2022-04-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='permission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.type_users'),
        ),
    ]
