# Generated by Django 4.0.2 on 2022-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='solicitud_especial',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredientes',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nombre_platillo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='descripcion',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='nombre_promocion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='name_restaurant',
            field=models.CharField(max_length=100),
        ),
    ]
