# Generated by Django 4.0.2 on 2022-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menus',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promotions',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
