# Generated by Django 4.0.2 on 2022-04-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_type_users_id_user_alter_users_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='permission',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='api.type_users'),
        ),
    ]
